export interface sendPost {
    userID: number; // Added userID to associate with user data
    caption: string;
    images?: string[];
  }


export interface retreivePost {
  id: number;  // Assuming this is auto-generated by the backend
  userID: number;
  caption: string;
  clothesUrl: string;
  images?: string[];
}

