stages:
  - deploy

deploy_to_s3:
  stage: deploy
  only:
    - main
  image: amazon/aws-cli:latest
  script:
    # Assume the role
    - echo "Assuming role for deployment"
    - |
      TEMP_ROLE=$(aws sts assume-role \
        --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/<GitLab-Deployment-Role> \
        --role-session-name gitlab-deployment)
      
      export AWS_ACCESS_KEY_ID=$(echo $TEMP_ROLE | jq -r '.Credentials.AccessKeyId')
      export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_ROLE | jq -r '.Credentials.SecretAccessKey')
      export AWS_SESSION_TOKEN=$(echo $TEMP_ROLE | jq -r '.Credentials.SessionToken')
      
    # Sync files to S3
    - echo "Deploying to S3 bucket - $S3_BUCKET"
    - aws s3 sync ./path/to/your/code s3://$S3_BUCKET/ --delete --region $AWS_REGION
  environment:
    name: production
    url: http://$S3_BUCKET.s3.amazonaws.com
