import { StyleSheet } from "react-native";

export const profileStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  topHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#f0f4ff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 24,
  },
  avatarContainer: {
    borderRadius: 999,
    overflow: "hidden",
  },
  statsContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  stat: {
    alignItems: "center",
  },
  statNumber: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#000",
  },
  statLabel: {
    fontSize: 12,
    color: "#888",
  },
  bioSection: {
    paddingHorizontal: 16,
    marginTop: 12,
  },
  nameText: {
    fontWeight: "bold",
    fontSize: 14,
    color: "#000",
  },
  bioText: {
    marginTop: 4,
    fontSize: 13,
    color: "#333",
  },
  linkText: {
    marginTop: 4,
    fontSize: 13,
    color: "#00376b",
    textDecorationLine: "underline",
  },
  editButtonWrapper: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  followedActionButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#007AFF",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  actionButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#007AFF",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  buttonLabel: {
    fontWeight: "600",
    fontSize: 14,
    color: "#007AFF",
  },
  subpageContainer: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  subpagePickerText: {
    fontSize: 14,
    color: "#888",
    paddingVertical: 6,
  },
  subpagePickerTextSelected: {
    fontSize: 14,
    color: "#000",
    fontWeight: "bold",
    borderBottomWidth: 2,
    borderColor: "#000",
    paddingVertical: 6,
  },
  gridContainer: {
    paddingHorizontal: 1,
  },
  postContainer: {
    flex: 1 / 3,
    aspectRatio: 1,
    margin: 1,
  },
  postImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  username: {
    fontSize: 20,
    fontWeight: "600",
    color: "#000",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modalSheet: {
    backgroundColor: "#fff",
    width: "100%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingVertical: 24,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
    color: "#000",
  },
  modalOption: {
    paddingVertical: 14,
  },
  modalOptionText: {
    fontSize: 16,
    color: "#007AFF",
    fontWeight: "500",
  },
  modalCancelText: {
    fontSize: 16,
    color: "#999",
    textAlign: "center",
    marginTop: 20,
  },
});
